{{/*
# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License
*/}}

{{- if .Values.pgpool.enable -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helper.names.fullname" . }}-scripts
  namespace: {{ include "helper.names.namespace" . | quote }}
  labels: 
    {{- include "helper.labels.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgpool
data:
  init-pgpool.sh: |
    #!/bin/bash
    set -euo pipefail

    # This script watch for the primary node to be ready and then initialize the pgpool configuration files.

    NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    PRIMARY={{ include "postgres.primaryName" .}}.$NS.svc.cluster.local
    SVC={{ include "postgres.headlessName" .}}.$NS.svc.cluster.local
    USER={{ .Values.pgpool.containerSecurityContext.runAsUser }}
    GROUP={{ .Values.pgpool.containerSecurityContext.runAsGroup }}

    echo "Waiting for primary to be ready..."
    until pg_isready -h $PRIMARY -p $POSTGRES_PORT -d $POSTGRES_DB -U $POSTGRES_USER; do
        echo "Waiting for primary to be ready..."
        sleep 5
    done
    echo "Primary is ready..."

    echo "Init data for pgpool"
    mkdir -p $PGPOOL_DATA/conf $PGPOOL_DATA/logs $PGPOOL_DATA/run && \
    chmod 750 $PGPOOL_DATA/conf $PGPOOL_DATA/logs $PGPOOL_DATA/run && \
    chown -R $USER:$GROUP $PGPOOL_DATA/conf $PGPOOL_DATA/logs $PGPOOL_DATA/run

    echo "Creating pcp.conf for pgpool..."
    HASH=$(printf '%s' "$PGPOOL_PASSWORD" | md5sum | awk '{print $1}')
    echo "# Generated by init container" > $PGPOOL_DATA/conf/pcp.conf
    echo "${PGPOOL_USER}:${HASH}" >> $PGPOOL_DATA/conf/pcp.conf
    echo "localhost:9898:${PGPOOL_USER}:${PGPOOL_PASSWORD}" > $PGPOOL_DATA/.pcppass
    chown -R $USER:$GROUP $PGPOOL_DATA/conf/pcp.conf $PGPOOL_DATA/.pcppass
    chmod 600 $PGPOOL_DATA/conf/pcp.conf $PGPOOL_DATA/.pcppass

    echo "Creating backends.conf for pgpool..."
    echo "# Generated by init container" > $PGPOOL_DATA/conf/backends.conf

    for i in $(seq 0 {{ .Values.pgpool.maxBackendNodes }}); do
      HOST=$(printf "{{ include "helper.names.fullname" . }}-%s" $i)
      echo "backend_hostname${i} = '${HOST}.${SVC}'" >> $PGPOOL_DATA/conf/backends.conf
      echo "backend_port${i} = ${POSTGRES_PORT}" >> $PGPOOL_DATA/conf/backends.conf
      echo "backend_weight${i} = 1" >> $PGPOOL_DATA/conf/backends.conf
      echo "backend_flag${i} = 'ALLOW_TO_FAILOVER'" >> $PGPOOL_DATA/conf/backends.conf
      echo "backend_application_name${i} = '${HOST}'" >> $PGPOOL_DATA/conf/backends.conf
    done

    chown -R $USER:$GROUP $PGPOOL_DATA/conf/backends.conf
    chmod 640 $PGPOOL_DATA/conf/backends.conf
  failover.sh: |
    #!/bin/bash
    set -euo pipefail

    # This script is called by pgpool-II when a backend node is detected as down.
    # It is responsible for promoting a standby server to primary and updating the pgpool configuration.
    
    echo "Starting failover process..."
    FAILED_NODE_ID=$1
    FAILED_HOST=$2
    NEW_MAIN_NODE_ID=$3
    NEW_MAIN_HOST=$4
    OLD_MAIN_NODE_ID=$5
    OLD_PRIMARY_NODE_ID=$6
    OLD_PRIMARY_HOST=$7

    if [ "$FAILED_NODE_ID" != "$OLD_PRIMARY_NODE_ID" ]; then
      echo "[FAILOVER] Standby failed ($FAILED_NODE_ID), no promotion required!"
      exit 0
    fi

    NEW_PRIMARY_POD_NAME="{{ include "helper.names.fullname" . }}-$NEW_MAIN_NODE_ID"
    OLD_PRIMARY_POD_NAME="{{ include "helper.names.fullname" . }}-$OLD_PRIMARY_NODE_ID"

    echo "[FAILOVER] Failed node: $FAILED_NODE_ID ($FAILED_HOST)"
    echo "[FAILOVER] New main node: $NEW_MAIN_NODE_ID ($NEW_MAIN_HOST)"
    echo "[FAILOVER] Old primary node: $OLD_PRIMARY_NODE_ID ($OLD_PRIMARY_HOST)"

    #
    # No new primary node available, exit gracefully
    #
    if [ "$NEW_MAIN_NODE_ID" -eq -1 ]; then
        echo "[FAILOVER] No new main node available"
        exit 0
    fi

    echo "[FAILOVER] Promoting pod $NEW_PRIMARY_POD_NAME"

    #
    # Promotion
    #
    psql -h $NEW_MAIN_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB \
      -tAc "SELECT pg_promote();" > /dev/null 2>&1

    #
    # Wait for promotion to complete
    #
    for i in $(seq 1 30); do
        RECOVERY=$(psql -h $NEW_MAIN_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -tAc \
              "SELECT pg_is_in_recovery();")

        if [ "$RECOVERY" = "f" ]; then
            echo "[FAILOVER] Promotion completed"
            TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
            NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
            CA=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            API="https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/api/v1/namespaces/${NS}/pods"

            echo "[FAILOVER] Removing role label from old primary pod ($OLD_PRIMARY_POD_NAME)..."
            wget -qO /dev/null \
              --ca-certificate=$CA \
              --header="Authorization: Bearer $TOKEN" \
              --header="Content-Type: application/strategic-merge-patch+json" \
              --method=PATCH --body-data='{"metadata":{"labels":{"role":"data"}}}' \
              "$API/$OLD_PRIMARY_POD_NAME"

            echo "[FAILOVER] Adding role label to new primary pod ($NEW_PRIMARY_POD_NAME)..."
            wget -qO /dev/null \
              --ca-certificate=$CA \
              --header="Authorization: Bearer $TOKEN" \
              --header="Content-Type: application/strategic-merge-patch+json" \
              --method=PATCH --body-data='{"metadata":{"labels":{"role":"data-primary"}}}' \
              "$API/$NEW_PRIMARY_POD_NAME"
            exit 0
        fi

        echo "[FAILOVER] Waiting for promotion..."
        sleep 1
    done

    echo "[FAILOVER] Promotion timeout"
    exit 1
  pgpool-watcher.sh: |
    #!/bin/bash
    set -euo pipefail

    echo "Starting pgpool watcher..."
    
    echo "Waiting for pgpool to be ready..."
    until pcp_node_count -h localhost -U $PGPOOL_USER -p 9898 -w > /dev/null 2>&1; do
      echo "Waiting for pgpool to be ready..."
      sleep 5
    done

    echo "Pgpool is ready..."

    while true; do
      for id in $(seq 0 {{ .Values.pgpool.maxBackendNodes }}); do
        INFO=$(pcp_node_info -h localhost -U $PGPOOL_USER -p 9898 -w -n $id)
        STATUS=$(echo $INFO | awk '{print $3}')
        DBHOST=$(echo $INFO | awk '{print $1}')

        if [ "$STATUS" -eq 3 ]; then
          
          if pg_isready -h "$DBHOST" -p $POSTGRES_PORT -U "$POSTGRES_USER" -d "$POSTGRES_DB" >/dev/null 2>&1 && \
              psql -h "$DBHOST" -p $POSTGRES_PORT -U "$POSTGRES_USER" -d "$POSTGRES_DB" -tAc "SELECT 1" >/dev/null 2>&1; then
            READY=1
          else
            READY=0
          fi

          # echo "Node $id ($DBHOST): status=$STATUS, ready=$READY"
          
          # ----------------------------
          # ATTACH LOGIC
          # ----------------------------
          if [ "$READY" -eq 1 ]; then
            echo "ATTACH node $id ($DBHOST)"

            pcp_attach_node \
              -h localhost \
              -U $PGPOOL_USER \
              -p 9898 \
              -w \
              -n $id
          fi

        fi

      done
      
      sleep 10 &
      wait $!
    done

    echo "pgpool watcher stopped."
  init-primary.sh: |
    #!/bin/bash
    set -euo pipefail

    # This script check if pod was previously primary and if so, it will reinitialize the pod as a standby node.
    # It's called by the postgres init container.
    ORDINAL="${POD_NAME##*-}"
    TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    CA=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    API="https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/api/v1/namespaces/${NS}/pods"
    PRIMARY={{ include "postgres.primaryName" .}}.$NS.svc.cluster.local
    SERVICE="{{ include "postgres.headlessName" . }}.$NS.svc.cluster.local"
    IPS=$(nslookup "$SERVICE" 2>/dev/null | awk '/^Address: / {print $2}')
    POD_EXISTS=0
    PGMOUNT={{ .Values.postgresql.persistence.mountPath }}

    echo "data" > ${PGMOUNT}/bootstrap-role

    for ip in $IPS; do
      if pg_isready -h "$ip" -U $POSTGRES_USER -d $POSTGRES_DB -p $POSTGRES_PORT >/dev/null 2>&1; then
        POD_EXISTS=1
      fi
    done

    # pod was a primary and other pods are ready then cleanup pgdata folder and reinitialize it
    if { [ -f "$PGDATA/PG_VERSION" ] && [ ! -f "$PGDATA/standby.signal" ] && [ "$POD_EXISTS" = "1" ]; } then
      echo "Previous primary pod detected and other pods are ready, cleaning up pgdata folder"
      rm -rf $PGDATA/*
      exit 0
    fi

    if { [ -f "$PGDATA/PG_VERSION" ] && [ ! -f "$PGDATA/standby.signal" ]; } || \
        { [ ! -f "$PGDATA/PG_VERSION" ] && [ "$ORDINAL" = "0" ] && [ "$POD_EXISTS" = "0" ]; } 
      then
      echo "I am the Primary, then modifying pod labels to role=data-primary"
      if wget -qO /dev/null \
        --ca-certificate=$CA \
        --header="Authorization: Bearer $TOKEN" \
        --header="Content-Type: application/strategic-merge-patch+json" \
        --method=PATCH --body-data='{"metadata":{"labels":{"role":"data-primary"}}}' \
        "$API/$POD_NAME"
      then
        echo "data-primary" > ${PGMOUNT}/bootstrap-role
        echo "Pod labels modified successfully"
        exit 0
      else
        echo "Failed to modify pod labels"
        exit 1
      fi
    else
      echo "I am a Standby, waiting for primary to be ready..."
      
      until pg_isready -h "$PRIMARY" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -p $POSTGRES_PORT >/dev/null 2>&1 && \
          psql -h "$PRIMARY" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -p $POSTGRES_PORT -tAc "SELECT 1" >/dev/null 2>&1; do
        echo "Waiting for primary to be ready..."
        sleep 5
      done

      echo "Primary is ready..."
      exit 0
    fi
  init-replica.sh: |
    #!/bin/bash
    set -euo pipefail

    # This script is called by the postgres init container when a pod is initialized as a standby node.
    # It will perform a base backup from the primary node to initialize the standby node.
    NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    PRIMARY={{ include "postgres.primaryName" .}}.$NS.svc.cluster.local
    # here we can't use k8s api because the pod is a postgres legacy image without wget 
    # so use what's as been provide by previous init script
    PGMOUNT={{ .Values.postgresql.persistence.mountPath }}
    USER={{ .Values.postgresql.containerSecurityContext.runAsUser }}
    GROUP={{ .Values.postgresql.containerSecurityContext.runAsGroup }}
    ROLE=$(cat ${PGMOUNT}/bootstrap-role)

    if [ -f "$PGDATA/PG_VERSION" ]; then
        echo "Already initialized, skipping replication setup!"
        exit 0
    fi

    if [ "$ROLE" = "data-primary" ]; then
      echo "I am the Primary then skipping replication setup!"
      exit 0
    fi

    echo "I am a Replica, starting replication..."
    echo "Waiting for primary to be ready..."

    until pg_isready -h "$PRIMARY" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -p $POSTGRES_PORT >/dev/null 2>&1 && \
        psql -h "$PRIMARY" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -p $POSTGRES_PORT -tAc "SELECT 1" >/dev/null 2>&1; do
      echo "Waiting for primary to be ready..."
      sleep 5
    done

    echo "Primary is ready..."

    until pg_basebackup \
      -d "host=${PRIMARY} user=${POSTGRES_USER} dbname=replication port=${POSTGRES_PORT} application_name=${POD_NAME}" \
      -D $PGDATA  -vP \
      --wal-method=stream; 
      do
        echo "Base backup failed, retrying..."
        sleep 5
    done

    touch $PGDATA/standby.signal
    cat > "$PGDATA/postgresql.auto.conf" <<EOF
    primary_conninfo = 'host=${PRIMARY} port=${POSTGRES_PORT} user=${POSTGRES_USER} application_name=${POD_NAME} dbname=replication passfile=${PGMOUNT}/conf/.pgpass'
    EOF
    chmod -R 700 $PGDATA && \
    chown -R ${USER}:${GROUP} $PGDATA
    echo "Base backup completed, replication setup is done."
    exit 0
  check-node-status.sh: |
    #!/bin/bash
    set -euo pipefail

    # Check if the PostgreSQL server is ready and if the current pod is a standby node, check if it is registered in the pool nodes list.
    pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -p $POSTGRES_PORT >/dev/null 2>&1 || exit 1
    psql -U $POSTGRES_USER -d $POSTGRES_DB -p $POSTGRES_PORT -c "SELECT 1" >/dev/null 2>&1 || exit 1

    if [ ! -f "$PGDATA/standby.signal" ]; then
        # Primary node, no need to check pool nodes
        exit 0
    fi

    NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    HOST="${POD_NAME}.{{ include "postgres.headlessName" . }}.${NS}.svc.cluster.local"
    SERVICE="{{ include "helper.names.fullname" . }}.${NS}.svc.cluster.local"

    PGPASSWORD=$POSTGRES_PASSWORD && psql -h $SERVICE \
        -U $POSTGRES_USER \
        -d $POSTGRES_DB \
        -Atc "SHOW POOL_NODES" |
    awk -F'|' -v host="$HOST" '
    {
        gsub(/^[ \t]+|[ \t]+$/, "", $2)   # hostname
        gsub(/^[ \t]+|[ \t]+$/, "", $4)   # status
        if ($2 == host && $4 == "up")
            found=1
    }
    END { exit(found ? 0 : 1) }'
{{- end -}}
