{{/*
# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helper.names.fullname" . }}
  namespace: {{ include "helper.names.namespace" . | quote }}
  labels: 
    {{- include "helper.labels.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
data:
  {{- if .Values.postgresql.configuration }}
  postgresql.conf: |-
    # From config map
    {{- include "helper.values.render" ( dict "value" .Values.postgresql.configuration "context" $ ) | nindent 4 }}
  {{- else }}
  postgresql.conf: |-
    # From config map
  {{- end }}
  {{- if .Values.pgpool.enable }}
    wal_level = replica
    wal_keep_size = 2GB
    max_wal_senders = 12
  {{- end }}
  {{- if .Values.postgresql.pgHbaConfiguration }}
  {{- include "helper.values.render" ( dict "value" .Values.postgresql.pgHbaConfiguration "context" $ ) | nindent 4 }}
  {{- else }}
  pg_hba.conf: |-
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    # "local" is for Unix domain socket connections only
    local   all             all                                     trust
    # IPv4 local connections:
    host    all             all             127.0.0.1/32            trust
    # IPv6 local connections:
    host    all             all             ::1/128                 trust
    # Allow replication connections from localhost, by a user with the
    # replication privilege.
    local   replication     all                                     trust
    host    replication     all             127.0.0.1/32            trust
    host    replication     all             ::1/128                 trust
    host    replication     all             all                     scram-sha-256
    host    all             all             all                     scram-sha-256
  {{- end }}
  {{- if .Values.pgpool.enable }}
  pgpool.conf: |-
    # From config map
    # Connection settings
    listen_addresses = '*'
    port = {{ .Values.pgpool.containerPort }}
    pcp_listen_addresses = '*'
    pcp_port = 9898
    unix_socket_directories = '/opt/pgpool/run'
    pcp_socket_dir = '/opt/pgpool/run'
    pid_file_name = '/opt/pgpool/run/pgpool.pid'
    # Logging settings
    log_directory = '/opt/pgpool/logs'
    logdir = '/opt/pgpool/logs'
    # Authentication settings
    enable_pool_hba = off
    pool_passwd = '/opt/pgpool/conf/pool_passwd'
    allow_clear_text_frontend_auth = on
    # Replication settings
    backend_clustering_mode = 'streaming_replication'
    load_balance_mode = on
    statement_level_load_balance = off
    disable_load_balance_on_write = 'transaction'
    sr_check_user = '{{ .Values.global.pgCheckUser  }}'
    sr_check_password = ''
    sr_check_database = '{{ .Values.global.pgDbName  }}'
    sr_check_period = 10
    include '/opt/pgpool/conf/backends.conf'
    failover_command = '/opt/scripts/failover.sh %d %h %m %H %M %P %N'
    # Healt check settings
    health_check_user = '{{ .Values.global.pgCheckUser  }}'
    health_check_password = ''
    health_check_period = 5
    health_check_timeout = 20
    health_check_max_retries = 0
  {{- end }}
    
    