{{/*
# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License
*/}}

{{- if .Values.pgpool.enable -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helper.names.fullname" . }}-scripts
  namespace: {{ include "helper.names.namespace" . | quote }}
  labels: 
    {{- include "helper.labels.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgpool
data:
  failover.sh: |
    #!/bin/bash
    set -euo pipefail

    # This script is called by pgpool-II when a backend node is detected as down.
    # It is responsible for promoting a standby server to primary and updating the pgpool configuration.
    
    echo "Starting failover process..."
    FAILED_NODE_ID=$1
    FAILED_HOST=$2
    NEW_MAIN_NODE_ID=$3
    NEW_MAIN_HOST=$4
    OLD_MAIN_NODE_ID=$5
    OLD_PRIMARY_NODE_ID=$6
    OLD_PRIMARY_HOST=$7

    if [ "$FAILED_NODE_ID" != "$OLD_PRIMARY_NODE_ID" ]; then
      echo "[FAILOVER] Standby failed ($FAILED_NODE_ID), no promotion required!"
      exit 0
    fi

    NEW_PRIMARY_POD_NAME="{{ include "helper.names.fullname" . }}-$NEW_MAIN_NODE_ID"
    OLD_PRIMARY_POD_NAME="{{ include "helper.names.fullname" . }}-$OLD_PRIMARY_NODE_ID"

    echo "[FAILOVER] Failed node: $FAILED_NODE_ID ($FAILED_HOST)"
    echo "[FAILOVER] New main node: $NEW_MAIN_NODE_ID ($NEW_MAIN_HOST)"
    echo "[FAILOVER] Old primary node: $OLD_PRIMARY_NODE_ID ($OLD_PRIMARY_HOST)"

    #
    # No new primary node available, exit gracefully
    #
    if [ "$NEW_MAIN_NODE_ID" -eq -1 ]; then
        echo "[FAILOVER] No new main node available"
        exit 0
    fi

    echo "[FAILOVER] Promoting pod $NEW_PRIMARY_POD_NAME"

    #
    # Promotion
    #
    psql -h $NEW_MAIN_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB \
      -tAc "SELECT pg_promote();" > /dev/null 2>&1

    #
    # Wait for promotion to complete
    #
    for i in $(seq 1 30); do
        RECOVERY=$(psql -h $NEW_MAIN_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -tAc \
              "SELECT pg_is_in_recovery();")

        if [ "$RECOVERY" = "f" ]; then
            echo "[FAILOVER] Promotion completed"
            TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
            NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
            CA=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            API="https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/api/v1/namespaces/${NS}/pods"

            echo "[FAILOVER] Removing role label from old primary pod ($OLD_PRIMARY_POD_NAME)..."
            wget -qO /dev/null \
              --ca-certificate=$CA \
              --header="Authorization: Bearer $TOKEN" \
              --header="Content-Type: application/strategic-merge-patch+json" \
              --method=PATCH --body-data='{"metadata":{"labels":{"role":"data"}}}' \
              "$API/$OLD_PRIMARY_POD_NAME"

            echo "[FAILOVER] Adding role label to new primary pod ($NEW_PRIMARY_POD_NAME)..."
            wget -qO /dev/null \
              --ca-certificate=$CA \
              --header="Authorization: Bearer $TOKEN" \
              --header="Content-Type: application/strategic-merge-patch+json" \
              --method=PATCH --body-data='{"metadata":{"labels":{"role":"data-primary"}}}' \
              "$API/$NEW_PRIMARY_POD_NAME"
            exit 0
        fi

        echo "[FAILOVER] Waiting for promotion..."
        sleep 1
    done

    echo "[FAILOVER] Promotion timeout"
    exit 1
  init-primary.sh: |
    #!/bin/bash
    set -euo pipefail

    # This script check if pod was previously primary and if so, it will reinitialize the pod as a standby node.
    # It's called by the postgres init container.
    ORDINAL="${POD_NAME##*-}"
    TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    CA=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    API="https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/api/v1/namespaces/${NS}/pods"

    SERVICE="{{ include "postgres.headlessName" . }}.$NS.svc.cluster.local"
    IPS=$(nslookup "$SERVICE" 2>/dev/null | awk '/^Address: / {print $2}')
    POD_EXISTS=0
    echo "data" > {{ .Values.postgresql.persistence.mountPath }}/bootstrap-role

    for ip in $IPS; do
      if pg_isready -h "$ip" -U $POSTGRES_USER -d $POSTGRES_DB -p $POSTGRES_PORT >/dev/null 2>&1; then
        POD_EXISTS=1
      fi
    done

    # pod was a primary and other pods are ready then cleanup pgdata folder and reinitialize it
    if { [ -f "$PGDATA/PG_VERSION" ] && [ ! -f "$PGDATA/standby.signal" ] && [ "$POD_EXISTS" = "1" ]; } then
      echo "Previous primary pod detected and other pods are ready, cleaning up pgdata folder"
      rm -rf $PGDATA/*
      exit 0
    fi

    if { [ -f "$PGDATA/PG_VERSION" ] && [ ! -f "$PGDATA/standby.signal" ]; } || \
        { [ ! -f "$PGDATA/PG_VERSION" ] && [ "$ORDINAL" = "0" ] && [ "$POD_EXISTS" = "0" ]; } 
      then
      echo "I am the Primary, then modifying pod labels to role=data-primary"
      if wget -qO /dev/null \
        --ca-certificate=$CA \
        --header="Authorization: Bearer $TOKEN" \
        --header="Content-Type: application/strategic-merge-patch+json" \
        --method=PATCH --body-data='{"metadata":{"labels":{"role":"data-primary"}}}' \
        "$API/$POD_NAME"
      then
        echo "data-primary" > {{ .Values.postgresql.persistence.mountPath }}/bootstrap-role
        echo "Pod labels modified successfully"
        exit 0
      else
        echo "Failed to modify pod labels"
        exit 1
      fi
    else
      echo "I am a Standby, waiting for primary to be ready..."
      PRIMARY={{ include "postgres.primaryName" .}}.$NS.svc.cluster.local
      until pg_isready -h "$PRIMARY" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -p $POSTGRES_PORT >/dev/null 2>&1 && \
          psql -h "$PRIMARY" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -p $POSTGRES_PORT -tAc "SELECT 1" >/dev/null 2>&1; do
        echo "Waiting for primary to be ready..."
        sleep 5
      done
      echo "Primary is ready..."
      exit 0
    fi
  init-replica.sh: |
    #!/bin/bash
    set -euo pipefail

    if [ ! -f "$PGDATA/standby.signal" ]; then
        echo "[INIT] Not a standby node, skipping initialization"
        exit 0
    fi

    echo "[INIT] Initializing standby node..."
    pg_basebackup -h $PRIMARY_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -D $PGDATA -Fp -Xs -P -R
    echo "[INIT] Standby node initialized successfully"
  check-node-status.sh: |
    #!/bin/bash
    set -euo pipefail

    # Check if the PostgreSQL server is ready and if the current pod is a standby node, check if it is registered in the pool nodes list.
    pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -p $POSTGRES_PORT >/dev/null 2>&1 || exit 1
    psql -U $POSTGRES_USER -d $POSTGRES_DB -p $POSTGRES_PORT -c "SELECT 1" >/dev/null 2>&1 || exit 1

    if [ ! -f "$PGDATA/standby.signal" ]; then
        # Primary node, no need to check pool nodes
        exit 0
    fi

    NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    HOST="${POD_NAME}.{{ include "postgres.headlessName" . }}.${NS}.svc.cluster.local"
    SERVICE="{{ include "helper.names.fullname" . }}.${NS}.svc.cluster.local"

    PGPASSWORD=$POSTGRES_PASSWORD && psql -h $SERVICE \
        -U $POSTGRES_USER \
        -d $POSTGRES_DB \
        -Atc "SHOW POOL_NODES" |
    awk -F'|' -v host="$HOST" '
    {
        gsub(/^[ \t]+|[ \t]+$/, "", $2)   # hostname
        gsub(/^[ \t]+|[ \t]+$/, "", $4)   # status
        if ($2 == host && $4 == "up")
            found=1
    }
    END { exit(found ? 0 : 1) }'
{{- end -}}
