{{/*
# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helper.names.fullname" . }}
  namespace: {{ include "helper.names.namespace" . | quote }}
  labels:
    {{- include "helper.labels.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
    role: data
type: Opaque
data:
  {{- if .Values.global.pgDbPassword }}
  POSTGRES_PASSWORD: {{ .Values.global.pgDbPassword | b64enc | quote }}
  {{- end }}