{{/*
# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helper.names.fullname" . }}
  namespace: {{ include "helper.names.namespace" . }}
  labels:
    {{- include "helper.labels.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  POSTGRES_PASSWORD: {{
      include "helper.secret.value" (dict
        "secretName" (include "helper.names.fullname" .)
        "namespace" (include "helper.names.namespace" .)
        "key" "POSTGRES_PASSWORD"
        "value" .Values.global.pgDbPassword
        "length" 32
      ) | quote
  }}
  POSTGRES_CHECK_PASSWORD: {{
      include "helper.secret.value" (dict
        "secretName" (include "helper.names.fullname" .)
        "namespace" (include "helper.names.namespace" .)
        "key" "POSTGRES_CHECK_PASSWORD"
        "value" .Values.global.pgCheckPassword
        "length" 32
      ) | quote
  }}
  {{- if .Values.pgpool.enable }}
  POSTGRES_REP_PASSWORD: {{
      include "helper.secret.value" (dict
        "secretName" (include "helper.names.fullname" .)
        "namespace" (include "helper.names.namespace" .)
        "key" "POSTGRES_REP_PASSWORD"
        "value" .Values.global.pgRepPassword
        "length" 32
      ) | quote
  }}
  PGPOOL_PASSWORD: {{
      include "helper.secret.value" (dict
        "secretName" (include "helper.names.fullname" .)
        "namespace" (include "helper.names.namespace" .)
        "key" "PGPOOL_PASSWORD"
        "value" .Values.global.pgPoolPassword
        "length" 32
      ) | quote
  }}
  {{- end }}