{{/*
# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.primaryName" .}}
  namespace: {{ include "helper.names.namespace" . | quote }}
  labels:
    {{- include "helper.labels.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  selector:
    {{- include "helper.labels.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
    role: data-primary
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP

