{{/*
# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License
*/}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "helper.names.fullname" . }}
  namespace: {{ include "helper.names.namespace" . }}
  labels:
    {{- include "helper.labels.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
    role: data
spec:
  serviceName: {{ printf "%s-hl" (include "helper.names.fullname" .) }}
  replicas: {{ .Values.postgresql.replicaCount }}
  podManagementPolicy: {{ .Values.postgresql.podManagementPolicy | quote }}
  updateStrategy: {{- toYaml .Values.postgresql.updateStrategy | nindent 4 }}
  selector:
    matchLabels: {{- include "helper.labels.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
      role: data
  template:
    metadata:
      labels:
        {{- include "helper.labels.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
        role: data
    spec:
      {{- include "helper.images.imagePullSecrets" (dict "imageRoot" .Values.postgresql.image "global" .Values.global) | nindent 6 -}}
      initContainers:
        - name: init-chmod-data
          image: {{ include "helper.images.image" (dict "imageRoot" .Values.postgresql.initImage "global" .Values.global) }}
          imagePullPolicy: {{ include "helper.images.pullPolicy" (dict "imageRoot" .Values.postgresql.image "global" .Values.global) }}
          command: ["sh", "-c", "chmod 700 /var/lib/postgresql/data"]
          volumeMounts:
            - name: data
              mountPath: /opt/postgresql/pgdata
      containers:
        - name: {{ include "helper.names.fullname" . }}
          image: {{ include "helper.images.image" (dict "imageRoot" .Values.postgresql.image "global" .Values.global "chart" .Chart) }}
          imagePullPolicy: {{ include "helper.images.pullPolicy" (dict "imageRoot" .Values.postgresql.image "global" .Values.global "chart" .Chart) }}
          ports:
            - name: postgresql
              containerPort: {{ .Values.postgresql.containerPort }}
              protocol: TCP
          {{- if .Values.postgresql.diagnosticModeEnabled }}
          command: {{- include "helper.values.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          args: {{- include "helper.values.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: PGDATA
              value: {{ printf "%s/%s" .Values.postgresql.persistence.mountPath "pgdata" | quote }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.postgresql.persistence.mountPath }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        labels:
          {{- include "helper.labels.labels" . | nindent 10 }}
          app.kubernetes.io/component: postgresql
          role: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.size }}
        {{- include "helper.names.storageClass" (dict "persistence" .Values.postgresql.persistence "global" .Values.global) | nindent 10 }}
    