{{/*
# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License
*/}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "helper.names.fullname" . }}
  namespace: {{ include "helper.names.namespace" . }}
  labels:
    {{- include "helper.labels.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
    role: data
spec:
  serviceName: {{ printf "%s-hl" (include "helper.names.fullname" .) }}
  replicas: {{ .Values.postgresql.replicaCount }}
  selector:
    matchLabels: {{- include "helper.labels.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
      role: data
  template:
    metadata:
      labels:
        {{- include "helper.labels.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
        role: data
    spec:
      {{- include "helper.images.imagePullSecrets" (dict "imageRoot" .Values.postgresql.image "global" .Values.global) | nindent 6 -}}
      containers:
        - name: {{ include "helper.names.fullname" . }}
          image: {{ include "helper.images.image" (dict "imageRoot" .Values.postgresql.image "global" .Values.global "chart" .Chart) }}
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: {{ .Values.postgresql.containerPort }}
              protocol: TCP
        