{{/*
# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License
*/}}

{{- if .Values.pgpool.enable -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.pgpoolName" . }}
  namespace: {{ include "helper.names.namespace" . }}
  labels:
    {{- include "helper.labels.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgpool
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "helper.labels.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pgpool
  template:
    metadata:
      labels:
        {{- include "helper.labels.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: pgpool
        role: pool
    spec:
      serviceAccountName: {{ include "postgres.serviceAccountName" . }}
      {{- include "helper.images.imagePullSecrets" (dict "imageRoot" .Values.pgpool "global" .Values.global) | nindent 6 }}
      {{- include "helper.pods.renderSecurityContext" (dict "securityContext" .Values.pgpool.podSecurityContext) | nindent 6 }}
      initContainers:
        - name: waiting-on-primary
          image: {{ include "helper.images.image" (dict "imageRoot" .Values.pgpool.initImage "global" .Values.global) }}
          imagePullPolicy: {{ include "helper.images.pullPolicy" (dict "imageRoot" .Values.pgpool.initImage "global" .Values.global) }}
          securityContext:
            runAsUser: 0
          env:
            - name: TZ
              value: {{ .Values.global.timezone | quote }}
            - name: PGPOOL_DATA
              value: /opt/pgpool
            - name: PGPOOL_USER
              value: {{ .Values.global.pgPoolUser | quote }}
            - name: PCPPASSFILE 
              value: /opt/pgpool/.pcppass
            - name: POSTGRES_PORT
              value: {{ .Values.postgresql.containerPort | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.global.pgDbName }}
            - name: POSTGRES_CHECK_USER
              value: {{ .Values.global.pgCheckUser | quote }}
            - name: PGPASSFILE
              value: /opt/pgpool/.pgpass
          command:
            - sh
          args:
            - -c
            - |
              /opt/scripts/init-pgpool.sh
          volumeMounts:
            - name: data
              mountPath: /opt/pgpool
            - name: scripts
              mountPath: /opt/scripts/init-pgpool.sh
              subPath: init-pgpool.sh
              readOnly: true
            - name: secrets
              mountPath: /run/secrets/postgresql
              readOnly: true
      containers:
        - name: {{ include "postgres.pgpoolName" . }}
          image: {{ include "helper.images.image" (dict "imageRoot" .Values.pgpool.image "global" .Values.global) }}
          imagePullPolicy: {{ include "helper.images.pullPolicy" (dict "imageRoot" .Values.pgpool.image "global" .Values.global) }}
          {{- include "helper.pods.renderSecurityContext" (dict "securityContext" .Values.pgpool.containerSecurityContext) | nindent 10 }}
          ports:
            - name: postgresql
              containerPort: {{ .Values.pgpool.containerPort }}
          {{- if .Values.pgpool.diagnosticModeEnabled }}
          command: {{- include "helper.values.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          args: {{- include "helper.values.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: TZ
              value: {{ .Values.global.timezone | quote }}
            - name: PGPOOL_DATA
              value: /opt/pgpool
            - name: PGPOOL_USER
              value: {{ .Values.global.pgPoolUser | quote }}
            - name: PCPPASSFILE 
              value: /opt/pgpool/.pcppass
            - name: POSTGRES_PORT
              value: {{ .Values.postgresql.containerPort | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.global.pgDbName | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.global.pgDbUser | quote }}
            - name: POSTGRES_CHECK_USER
              value: {{ .Values.global.pgCheckUser | quote }}
            - name: PGPASSFILE
              value: /opt/pgpool/.pgpass
          {{- if not .Values.pgpool.diagnosticModeEnabled }}
          startingProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pcp_node_count -h localhost -U $PGPOOL_USER -p 9898 -w > /dev/null 2>&1
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pcp_node_count -h localhost -U $PGPOOL_USER -p 9898 -w > /dev/null 2>&1
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  pcp_node_count -h localhost -U $PGPOOL_USER -p 9898 -w > /dev/null 2>&1
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /opt/pgpool
            - name: config
              mountPath: /opt/pgpool/conf/pgpool.conf
              subPath: pgpool.conf
            - name: scripts
              mountPath: /opt/scripts/failover.sh
              subPath: failover.sh
        - name: {{ include "postgres.pgpoolName" . }}-watcher
          image: {{ include "helper.images.image" (dict "imageRoot" .Values.pgpool.image "global" .Values.global) }}
          imagePullPolicy: {{ include "helper.images.pullPolicy" (dict "imageRoot" .Values.pgpool.image "global" .Values.global) }}
          {{- include "helper.pods.renderSecurityContext" (dict "securityContext" .Values.pgpool.containerSecurityContext) | nindent 10 }}
          env:
            - name: TZ
              value: {{ .Values.global.timezone | quote }}
            - name: PGPOOL_DATA
              value: /opt/pgpool
            - name: PGPOOL_USER
              value: {{ .Values.global.pgPoolUser }}
            - name: PCPPASSFILE 
              value: /opt/pgpool/.pcppass
            - name: POSTGRES_PORT
              value: {{ .Values.postgresql.containerPort | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.global.pgDbName | quote }}
            - name: POSTGRES_CHECK_USER
              value: {{ .Values.global.pgCheckUser | quote }}
            - name: PGPASSFILE
              value: /opt/pgpool/.pgpass
          command:
            - sh
          args:
            - -c
            - |
              /opt/scripts/pgpool-watcher.sh
          volumeMounts:
            - name: data
              mountPath: /opt/pgpool
            - name: scripts
              mountPath: /opt/scripts/pgpool-watcher.sh
              subPath: pgpool-watcher.sh
              readOnly: true
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "helper.names.fullname" . }}
            defaultMode: 0440
        - name: scripts
          configMap:
            name: {{ include "helper.names.fullname" . }}-scripts
            defaultMode: 0550
        - name: secrets
          secret:
            secretName: {{ include "helper.names.fullname" . }}
            defaultMode: 0440
{{- end -}}