{{/*
# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License
*/}}

{{- if .Values.pgpool.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helper.names.fullname" . }}
  namespace: {{ include "helper.names.namespace" . }}
  labels:
    {{- include "helper.labels.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgpool
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "helper.labels.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pgpool
      role: pool
  template:
    metadata:
      labels:
        {{- include "helper.labels.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: pgpool
        role: pool
    spec:
      serviceAccountName: {{ include "helper.names.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}-pgpool
          image: {{ include "helper.images.image" (dict "imageRoot" .Values.pgpool.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.pgpool.image.pullPolicy }}
          ports:
            - name: pgpool
              containerPort: {{ .Values.pgpool.containerPort }}
          {{- if .Values.pgpool.diagnosticModeEnabled }}
          command: {{- include "helper.values.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          args: {{- include "helper.values.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: TZ
              value: {{ .Values.global.timezone }}
{{- end -}}