{{/*
# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License
*/}}

{{- if and .Values.pgpool.enable .Values.pgpool.tls.enable -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tls" (include "postgres.pgpoolName" .) }}
  namespace: {{ include "helper.names.namespace" . }}
  labels:
    {{- include "helper.labels.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgpool
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.pgpool.tls.crt | b64enc | quote }}
  tls.key: {{ .Values.pgpool.tls.key | b64enc | quote }}
{{- end -}}
