{{/*
# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License
*/}}

{{- if .Values.pgpool.enable -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helper.names.fullname" . }}
  namespace: {{ include "helper.names.namespace" . }}
  labels:
    {{- include "helper.labels.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end -}}