apiVersion: v2
type: application
name: postgres
description: A Helm chart for Postgresql database including
    pg_pool addon for connection pooling.

maintainers:
  - name: Eric Grossi / FreeCharts
    url: https://github.com/freecharts

version: 18.3
appVersion: "18.3"


