# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License

apiVersion: v2
type: application
name: postgres
description: A Helm chart for Postgresql database including
    pg_pool addon for connection pooling.
home: https://github.com/freecharts/helm
keywords:
  - postgres
  - postgresql
  - database
  - pg_pool
maintainers:
  - name: Eric Grossi / FreeCharts
    url: https://github.com/freecharts
annotations:
  licence: MIT License
dependencies:
  - name: helper
    version: 1.0.0
    repository: "file://../helper"
version: 1.0.0
appVersion: "18.3"


