# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License

## @param nameOverride This is to override the chart name.
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global default StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  imagePullSecrets: []
  pullPolicy: ""
  storageClass: ""
  defaultStorageClass: ""
  pgDbName: "postgres"
  pgDbUser: "postgres"
  pgDbPassword: "change_me"
## @param diagnosticMode Diagnostic mode in the deployment
##
diagnosticMode:
  ## @param diagnosticMode.command [array] Command to override all containers in the deployment
  ##
  command:
    - sleep
  ## @param diagnosticMode.args [array] Args to override all containers in the deployment
  ##
  args:
    - infinity

## Default values for postgres.
postgresql:
  ## @param postgresql.diagnosticModeEnabled This set diagnostic mode for PostgreSQL deployment, more information can be found here: https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-debug-containers
  diagnosticModeEnabled: false
  ## @param postgresql.imagePullSecrets this set image pull secrets for both init and main container, more information can be found here: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
  imagePullSecrets: []
  ## @param postgresql.initImage This sets the container init image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  initImage:
    registry: ""
    repository: "busybox"
    tag: "1.34.1"
    digest: ""
    pullPolicy: ""
  ## @param postgresql.image This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    registry: ""
    repository: "postgres"
    tag: ""
    digest: ""
    ## default pull policy is 'IfNotPresent' if the tag is not 'latest', otherwise 'Always'
    pullPolicy: ""
  ## @param postgresql.replicaCount This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicaCount: 1
  ## @param postgresql.containerPort This sets the container port, more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  containerPort: 5432
  ## @param postgresql.headlessWithNotReadyAddresses set postgres headless service into publishNotReadyAddresses mode
  ## It can be used to minimize/eliminate Pgpool-II restarts during PostgreSQL rolling upgrades or edge-case situations like
  ## network split. It expects that no other external component will use PostgreSQL headless service to connect or that
  ## such component implements re-try logic.
  ## This mode also enables enriched readiness probe implementation which delays first switch of POD to READY state
  ## after start/restart of container. It gives Pgpool-II time switch node back from DOWN to UP state during rolling
  ## upgrade.
  ##
  headlessWithNotReadyAddresses: false
  ## Persistence configuration for PostgreSQL data. More information can be found here: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  persistence:
    ## @param postgresql.persistence.storageClass Storage class for persistence
    storageClass: ""
    ## @param postgresql.persistence.mountPath The path the volume will be mounted at, useful when using different PostgreSQL images.
    ##
    mountPath: /opt/postgresql
    ## @param postgresql.persistence.subPath SubPath for the data volume, useful when using different PostgreSQL images.
    subPath: ""
    ## @param postgresql.persistence.size Size for persistence
    size: 8Gi
  ## @param postgresql.updateStrategy.type Postgresql StatefulSet strategy type
  ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
  ## e.g:
  ## updateStrategy:
  ##  type: RollingUpdate
  ##  rollingUpdate:
  ##    maxSurge: 25%
  ##    maxUnavailable: 25%
  ##
  updateStrategy:
    type: RollingUpdate
  ## @param postgresql.podManagementPolicy Sets the pod management policy
  ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-management-policies
  ##
  podManagementPolicy: Parallel
  ## You can use this parameter to specify the content for postgresql.conf
  ## Example:
  ## configuration: |-
  ##   listen_addresses = '*'
  ##   port = '5432'
  ##   ...
  ##
  configuration: ""
  ## You can use this parameter to specify the content for pg_hba.conf
  ## Otherwise, a pg_hba.conf will be generated automaticly
  ## Example:
  ## pgHbaConfiguration: |-
  ##   host     all            repmgr    0.0.0.0/0    md5
  ##   host     repmgr         repmgr    0.0.0.0/0    md
  ##   ...
  ##
  pgHbaConfiguration: ""
  ## @param postgresql.podSecurityContext Security context for PostgreSQL pods, 
  ## more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  podSecurityContext:
    fsGroupChangePolicy: OnRootMismatch
    fsGroup: 999
  ## Container Security Context
  ## https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ## e.g:
  ##   containerSecurityContext:
  ##     capabilities:
  ##       drop: ["NET_RAW"]
  ##     readOnlyRootFilesystem: true
  ##
  containerSecurityContext:
    runAsUser: 999
    runAsGroup: 999
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"

## @param pgpool Default values for pgpool.
pgpool:
  enable: false
  ## This sets the container image, more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    registry: ""
    repository: "pgpool"
    tag: "4.7.1"
    pullPolicy: IfNotPresent

## This is for setting up a service, more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  portName: "tcp-postgres"
  ## @param service.port This sets the ports, more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 5432

